site :opscode

cookbook 'php'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'postgresql'
cookbook 'openssl'
cookbook 'postfix'
cookbook 'chef-php-extra', git: 'git://github.com/inviqa/chef-php-extra'
cookbook 'redis', git: 'git://github.com/miah/chef-redis'
cookbook 'beanstalkd', git: 'git://github.com/escapestudios/chef-beanstalkd'
cookbook 'npm', git: 'git://github.com/balbeko/chef-npm'
cookbook 'apache2', git: 'git://github.com/minicodemonkey/chef-apache24'
cookbook 'laravel', git: 'git://github.com/minicodemonkey/chef-laravel'
cookbook 'beanstalk_console', git: 'git://github.com/minicodemonkey/chef-beanstalk_console'