site :opscode

cookbook 'apache2'
cookbook 'php'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'postgresql'
cookbook 'openssl'
cookbook 'postfix'
cookbook 'chef-php-extra', git: 'git://github.com/inviqa/chef-php-extra'
cookbook 'redis', git: 'git://github.com/miah/chef-redis'
cookbook 'beanstalkd', git: 'git://github.com/escapestudios/chef-beanstalkd'
cookbook 'laravel', path: './site-cookbooks/laravel'